name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ runner.temp }}/android-sdk
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk

    steps:
    - name: Install required system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y tar unzip wget

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK + cmdline-tools
      run: |
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
        unzip -qq tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
        rm tools.zip

        export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "build-tools;34.0.0" \
          "platforms;android-34" \
          "cmdline-tools;latest"

    - name: Build APKs
      run: |
        export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        chmod +x ./gradlew
        ./gradlew assembleDebug --stacktrace --no-daemon

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: built-apks
        path: app/build/outputs/apk/**/*.apk
