name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tar unzip wget

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Define ANDROID_SDK path
        run: |
          echo "ANDROID_SDK=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_HOME=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$RUNNER_TEMP/android-sdk" >> $GITHUB_ENV

      - name: Install Android SDK + cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK/cmdline-tools/latest
      
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip -qq tools.zip -d $ANDROID_SDK/cmdline-tools/latest
          rm tools.zip
      
          export PATH=$PATH:$ANDROID_SDK/cmdline-tools/latest/cmdline-tools/bin
      
          yes | sdkmanager --licenses
      
          sdkmanager \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-34"

      - name: Build APK
        run: |
          export PATH=$PATH:$ANDROID_SDK/platform-tools:$ANDROID_SDK/cmdline-tools/latest/cmdline-tools/bin
          chmod +x ./gradlew
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: app/build/outputs/apk/**/*.apk
              
